### ISSUE TITLE
Requirements table generator has a bug. The generated tables are broken due to spaces in the second line ("| -- | -- |")

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-SIP#16]
<img width="894" alt="screenshot 2018-12-19 at 14 38 30" src="https://user-images.githubusercontent.com/3181302/50227024-9fa9d600-039c-11e9-96df-8f2c579330e2.png">

I fixed them manually, meanwhile.

It should be:

```
| ID | Name & Location | Description & usage | Cardinality & Level |
|----|-----------------|---------------------|-------------------- |
```

Instead of:

```
| ID | Name & Location | Description & usage | Cardinality & Level |
| -- | --------------- | ------------------- | ------------------- |
```

**Comment by jmaferreira** [comment]
Actually, I think the problem is on the first column:

This fails:

```
| --  |
```

This is ok:

```
| ---  |
```

**Comment by carlwilson** [comment]
@jmaferreira what Markdown renderer are you using. I've used a few when developing this and there are some inconsistencies. My iniital use case was producing Markdown that was suitable for the Jekyll renderer used to produce GH pages. I even found discrepancies between that and the local version of Jekyll I used. I also checked things through a Markdown plugin for GitHubs Atom text editor.

**Comment by jmaferreira** [comment]
I get that for sure. I'm using a desktop app called MacDown (for macOS). It makes my life easier when editing these documents.

**Comment by carlwilson** [comment]
So Markdown flavours are a little fussy and tables are one of the worst as they're not covered in the Daring Fireball original markdown specification meaning impelmentations differ. My issue here is that I distinclty remember having to set these table headers specifically so they played nicely on both the renderers I mentioned. It appears the addition of a new interpreter and renderer is the root cause of the issue. I'm loth to change this until I'm sure that it works properly with the other renderers I mentioned.

**Comment by jmaferreira** [comment]
Lets close this. Its probably an issue of my application.

**Comment by carlwilson** [comment]
I'll leave it briefly as I'll see if I can find an approach that works for all 3, but won't burn too much time on it.
