### ISSUE TITLE
The cardinality of METS element SIP12 assumes that there can only be one archival creator for a SIP (Cardinality 0..1)

### ISSUE THREAD

**Issue by jmaferreira** [DILCISBoard/E-ARK-SIP#25]
Page 13, METS element SIP12 (Archival creator agent name): The cardinality of METS element SIP12 assumes that there can only be one archival creator for a SIP (Cardinality 0..1). However, in real life this is not always the case. To accommodate those situations the cardinality should be 0..*. (A real-life example that I came across recently is three independent and autonomous public authorities that use the same database installation. In this case I need to be able to have all three authorities as archival creators.)
--

**Comment by jmaferreira** [comment]
@karinbredenberg I need some help in here.
The reviewer gives a counter example for our approach to cardinality of the agent that prepares and sends the SIP.

What do you think about his?

**Comment by karinbredenberg** [comment]
Not sure how to think here, are they in the final end having a combined archive? My guess is not. 
There are no problem with a different cardinality, To make it easier to adopt perhaps change? And rlet others restrict it further in local implementation.
I'm wonder though when they transfer the information to the archives, can be due to the regulations they are seen as combined archival creators. You most certain need to have the information about the database being created by more than one, but I'm not sure that is needed in a SIP package?

**Comment by jmaferreira** [comment]
I've added support for 0..* cardinality. The example given makes sense and there is no harm in supporting multiple creators.
